/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "uart.h"
#include "dma.h"

#define BUFFER_SIZE 32
#define DMA_STREAM_IRQHANDLER    DMA2_Stream0_IRQHandler


extern DMA_HandleTypeDef DmaHandle;

static const uint32_t SRC_Const_Buffer[BUFFER_SIZE]= {
                                    0x01020304,0x05060708,0x090A0B0C,0x0D0E0F10,
                                    0x11121314,0x15161718,0x191A1B1C,0x1D1E1F20,
                                    0x21222324,0x25262728,0x292A2B2C,0x2D2E2F30,
                                    0x31323334,0x35363738,0x393A3B3C,0x3D3E3F40,
                                    0x41424344,0x45464748,0x494A4B4C,0x4D4E4F50,
                                    0x51525354,0x55565758,0x595A5B5C,0x5D5E5F60,
                                    0x61626364,0x65666768,0x696A6B6C,0x6D6E6F70,
                                    0x71727374,0x75767778,0x797A7B7C,0x7D7E7F80};

static uint32_t DST_Buffer[BUFFER_SIZE];

static void TransferComplete(DMA_HandleTypeDef *DmaHandle); //callback functions with user picked custom function names
static void TransferError(DMA_HandleTypeDef *DmaHandle); //callback functions with user picked custom function names

static void register_callback_functions(void);

int main(void)
{
	HAL_Init();
	uart_init();

	enable_clock_access_to_dma();
	dma_config();
	initialize_dma();
	register_callback_functions();
	set_priority_enable_dma_interrupt();

	HAL_DMA_Start_IT(&DmaHandle, (uint32_t)&SRC_Const_Buffer, (uint32_t)&DST_Buffer, BUFFER_SIZE); // Start the DMA Transfer with interrupt enabled

    /* Loop forever */
	for(;;)
	{


	}
}

static void register_callback_functions(void)
{
	HAL_DMA_RegisterCallback(&DmaHandle, HAL_DMA_XFER_CPLT_CB_ID, TransferComplete);
	HAL_DMA_RegisterCallback(&DmaHandle, HAL_DMA_XFER_ERROR_CB_ID, TransferError);
}


static void TransferComplete(DMA_HandleTypeDef *DmaHandle)
{
	//Do something..
	printf("Transfer complete!! \n\r");
}


static void TransferError(DMA_HandleTypeDef *DmaHandle)
{
	//Do something...
	printf("Transfer Error!! \n\r");
}


void DMA_STREAM_IRQHANDLER(void)
{
    HAL_DMA_IRQHandler(&DmaHandle);
}


void  SysTick_Handler(void)
{
	HAL_IncTick();
}


