/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 STM32 Nucleo-144 boards (MB1137)

Inside the microcontroller of the STM32 Nucleo 144 board, the USART3 is connected to the USB. Hence we are going to use the USART3 in this application
If we used another USART than USART3, then we should have used a Serial to USB converter connected with that USART.

 ******************************************************************************
 */
#include "stm32f4xx_hal.h"
#include <stdint.h>
#include "uart.h"

extern UART_HandleTypeDef h_uart_1;

void uart1_init(void);

char message[20] = "Hello from Cornel IoT!\n\r";


uint8_t button_status;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	HAL_Init();
	uart3_init();

    /* Loop forever */
	for(;;)
	{

		//HAL_StatusTypeDef HAL_UART_Transmit (UART_HandleTypeDef * huart, const uint8_t * pData, uint16_t Size, uint32_t Timeout)
		HAL_UART_Transmit (&h_uart_1,(uint8_t *) message, 21, 100);
		HAL_Delay(10);
	}
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
