/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 STM32 Nucleo-144 boards (MB1137)
 * Push-buttons
B1 USER: the user button is connected to the I/O PC13 by default (Tamper support, SB173 ON and SB180 OFF) or PA0 (Wakeup support, SB180 ON and SB173 OFF) of the STM32 microcontroller.

User LD1: a green user LED is connected to the STM32 I/O PB0 (SB120 ON and SB119 OFF) or PA5 (SB119 ON and SB120 OFF) corresponding to the ST Zio D13.
User LD2: a blue user LED is connected to PB7. >> I am going to use this User Led for the example
User LD3: a red user LED is connected to PB14.
These user LEDs are on when the I/O is HIGH value, and are off when the I/O is LOW.
 *
 ******************************************************************************
 */
#include "stm32f4xx_hal.h"
#include <stdint.h>

#define BTN_PIN	GPIO_PIN_13
#define BTN_PORT	GPIOC

#define BLUE_USER_LED_PIN	GPIO_PIN_7
#define BLUE_USER_LED_PORT	GPIOB

#define RED_USER_LED_PIN GPIO_PIN_14
#define RED_USER_LED_PORT GPIOB

void pb7_blue_led_init(void);
void pb14_red_led_init(void);
void pc13_button_init(void);
void SysTick_Handler(void);

uint8_t button_status;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	HAL_Init();
	pc13_button_init();
	pb7_blue_led_init();
	pb14_red_led_init();


    /* Loop forever */
	for(;;)
	{

		button_status=HAL_GPIO_ReadPin(BTN_PORT, BTN_PIN);
		HAL_GPIO_WritePin(BLUE_USER_LED_PORT,BLUE_USER_LED_PIN, button_status);
		HAL_GPIO_WritePin(RED_USER_LED_PORT,RED_USER_LED_PIN, button_status);


	}
}

void pb7_blue_led_init(void)
{

	/* Enable clock access to GPIO B */
	__HAL_RCC_GPIOB_CLK_ENABLE();

	/* Configure the PB 7 and PB 14 as output pins */
	GPIO_InitTypeDef GPIO_Green_InitStructure = {0};

	GPIO_Green_InitStructure.Pin = BLUE_USER_LED_PIN;
	GPIO_Green_InitStructure.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_Green_InitStructure.Pull = GPIO_NOPULL;
	GPIO_Green_InitStructure.Speed = GPIO_SPEED_FREQ_LOW;

	/* initialize  the GPIO to be ready for use */
	HAL_GPIO_Init(BLUE_USER_LED_PORT, &GPIO_Green_InitStructure);

}

void pb14_red_led_init(void)
{
	/* Enable clock access to GPIO B */
	//__HAL_RCC_GPIOB_CLK_ENABLE();


	GPIO_InitTypeDef GPIO_Red_InitStructure = {0};

	GPIO_Red_InitStructure.Pin = RED_USER_LED_PIN;
	GPIO_Red_InitStructure.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_Red_InitStructure.Pull = GPIO_NOPULL;
	GPIO_Red_InitStructure.Speed = GPIO_SPEED_FREQ_LOW;

	/* initialize  the GPIO to be ready for use */
	HAL_GPIO_Init(RED_USER_LED_PORT, &GPIO_Red_InitStructure);
}

void pc13_button_init(void)
{
	/* Enable clock access to GPIO C */
	__HAL_RCC_GPIOC_CLK_ENABLE();


	/* Configure the PC13 as input pins */
	GPIO_InitTypeDef GPIO_Button_InitStructure ={0};

	GPIO_Button_InitStructure.Pin = BTN_PIN;
	GPIO_Button_InitStructure.Mode = GPIO_MODE_INPUT;
	GPIO_Button_InitStructure.Pull = GPIO_NOPULL;
	GPIO_Button_InitStructure.Speed = GPIO_SPEED_FREQ_LOW;

	/* initialize  the GPIO to be ready for use */
	HAL_GPIO_Init(BTN_PORT, &GPIO_Button_InitStructure);

}

void SysTick_Handler(void)
{
	HAL_IncTick();
}
