/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 STM32 Nucleo-144 boards (MB1137)

 The information about the Pins associated to USART1 is derived from "STM32F427xx and STM32F429xx alternate function mapping" in the STM32F429ZI Datasheet: PA9 ->USART1_TX ; PA10 -> USART1_RX

 For verification connect a jumper wire with an end to PA9 and the other end to PA10, and you should observe in debug mode that the global variable counters increase, and the buffers(arrays) get filled at the rx end.

 ******************************************************************************
 */


#include "stm32f4xx_hal.h"
#include <stdint.h>
#include "uart.h"
#include "rtc.h"
#include <stdio.h>

extern UART_HandleTypeDef h_uart_1;
extern RTC_HandleTypeDef RtcHandle;


void uart_init(void);

uint8_t time[10]={0};
uint8_t date[10]={0};


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	HAL_Init();
	uart_init();

	reset_handle_state();
	turn_off_LSE_turn_on_LSI();
	set_clock_source_to_LSI();
	enable_RTC_clock();

	configure_calendar();

	if(HAL_RTCEx_BKUPRead(&RtcHandle, RTC_BKP_DR0) != WRITE_FLAG_BACKUP_REGISTRY)
	  {
		 set_calendar();
	  }

	for(;;)
	{
		show_calendar(time, date);
	}
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}



