/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "adc.h"
#include "uart.h"

extern ADC_HandleTypeDef hadc1;
extern DMA_HandleTypeDef hdma_adc1;

uint32_t sensor_value[2]; //it has to be an array because we transfer from the peripheral to a buffer which is abstracted by an array

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	HAL_Init();
	uart_init();
	adc_pa1pa2_dma_init();
	set_priority_enable_interrupt_for_dma();
	configure_dma();
	link_adc_TO_DMA();

	HAL_ADC_Start_DMA(&hadc1,(uint32_t *)sensor_value,2);


    /* Loop forever */
	for(;;)
	{
		  printf("Sensor 1 data :  %d \n\r",(int)sensor_value[0]);
		  printf("Sensor 2 data :  %d \n\r",(int)sensor_value[1]);
	}
}


void  SysTick_Handler(void)
{
	HAL_IncTick();
}


void ADC_IRQHandler(void)
{
	HAL_ADC_IRQHandler(&hadc1);
}

void DMA2_Stream0_IRQHandler(void)
{
	HAL_DMA_IRQHandler(&hdma_adc1);
}
